### ISSUE TITLE
Bot reacts to multiline brace pairs and empty brace pairs

### ISSUE THREAD

**Issue by eritbh** [dashwav/Discordoragi#3]
When talking with someone about CSS issues, I posted a block of code that had braces in it, and discordoragi reacted with an X as if I'd tried to link an invalid anime. The same thing happened when I posted a message that just contained `{}`. These are cases where it should be clear the user's intent is not to link an anime, and I don't think the bot should react in these situations.

It would also be cool if the bot ignored all input inside inline or block code.

Exact message texts:

````
For the discord button, you'll want this:
```css
a[href="https://discord.gg/2Kk7rMa"] {
    display: block;
    text-align: center;
}
```
(you can then remove the `text-align` rule from the `::after` element)
````

```
also does discordoragi react to anything with {} even if it's multiline because that seems dumb
```

```
ooh I guess it just reacts on {}
```

**Comment by dashwav** [comment]
Looking into this now, I have known for a while I need to clean up the regex, thanks for the heads up!

**Comment by dashwav** [comment]
Should be fixed with latest update - Sorry for the late response!
